# Generated by Django 5.0.6 on 2024-07-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='store',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tel',
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='バンド名'),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
